<script setup lang="ts">
import { computed, reactive, ref } from 'vue';
import { createLegacyServices, getTodayStr } from '../services/legacyServices';
import { useLifePlanStore } from '../stores/lifePlanStore';
import { useTodosStore } from '../stores/todosStore';
const store = useLifePlanStore(); const todos = useTodosStore(); const ai = createLegacyServices().ai;
const config = reactive(ai.normalizeConfig(JSON.parse(localStorage.getItem('lifePlanAiConfig') || '{}'))); const input = ref(''); const result = ref<any>(null); const running = ref(false); const error = ref('');
const context = computed(() => ({ todayTodos: store.data.todos.filter(todo => !todo.done && todo.dueDate === getTodayStr()), floatingTodos: store.data.todos.filter(todo => !todo.done && !todo.dueDate), overdueTodos: store.data.todos.filter(todo => !todo.done && todo.dueDate && todo.dueDate < getTodayStr()) }));
function saveConfig() { Object.assign(config, ai.normalizeConfig(config)); localStorage.setItem('lifePlanAiConfig', JSON.stringify(config)); }
async function run() { running.value = true; error.value = ''; const payload = { mode: 'chatCapture', userInput: input.value, today: getTodayStr(), context: context.value }; try { result.value = ai.isRemoteReady(config) ? await ai.requestRemoteAi(config, payload) : ai.generateLocalAiResult(payload); } catch (err) { error.value = err instanceof Error ? err.message : String(err); } finally { running.value = false; } }
function apply(item: any) { todos.create({ text: item.text, note: item.note || '', dueDate: item.dueDate || '', planStartDate: item.planStartDate || '', planEndDate: item.planEndDate || '', urgency: item.urgency || 'medium', group: item.group || '其他' }); }
</script>
<template><section class="page active"><header class="page-header"><div class="page-title">AI 助手</div></header><article class="card"><div class="card-title">AI 设置</div><div class="form-row"><div class="form-group"><label>接口地址</label><input v-model="config.endpointUrl" placeholder="https://.../v1" /></div><div class="form-group"><label>模型</label><input v-model="config.model" /></div><div class="form-group"><label>API Key</label><input v-model="config.apiKey" type="password" /></div><div class="form-group"><label><input v-model="config.remoteEnabled" type="checkbox" /> 启用远程 AI</label></div></div><button class="btn btn-secondary" @click="saveConfig">保存设置</button></article><article class="card"><div class="card-title">对话整理</div><textarea v-model="input" placeholder="输入一段想法、日记或待办……"></textarea><button class="btn btn-primary" :disabled="running" @click="run">{{ running ? '整理中…' : '生成建议' }}</button><p v-if="error" class="form-error">{{ error }}</p></article><article v-if="result" class="card"><div class="card-title">{{ result.title }}</div><p>{{ result.summary }}</p><div class="ai-result-list"><div v-for="(item, index) in result.items" :key="index" class="ai-result-item"><strong>{{ item.text }}</strong><p>{{ item.note }}</p><button class="btn btn-secondary" @click="apply(item)">创建待办</button></div></div></article></section></template>
