<script setup lang="ts">
import { computed, reactive } from 'vue';
import { createLegacyServices, getTodayStr } from '../services/legacyServices';
import { useLifePlanStore } from '../stores/lifePlanStore';
const store = useLifePlanStore(); const fitness = createLegacyServices().fitness;
const form = reactive({ date: getTodayStr(), weight: '', bodyFat: '', waist: '', note: '' });
const metrics = computed(() => store.data.bodyMetrics.slice().sort((a, b) => String(b.date || '').localeCompare(String(a.date || ''))));
function save() { const result = fitness.upsertBodyMetric(store.data.bodyMetrics, { date: form.date, weight: Number(form.weight) || undefined, bodyFat: Number(form.bodyFat) || undefined, waist: Number(form.waist) || undefined, note: form.note }); if (!result.ok) return; store.data.bodyMetrics = result.metrics; store.commit('upsert-body-metric'); Object.assign(form, { date: getTodayStr(), weight: '', bodyFat: '', waist: '', note: '' }); }
</script>
<template><section class="page active"><header class="page-header"><div class="page-title">运动健身</div></header><form class="card" @submit.prevent="save"><div class="card-title">记录身体指标</div><div class="form-row"><div class="form-group"><label>日期</label><input v-model="form.date" type="date" /></div><div class="form-group"><label>体重 (kg)</label><input v-model="form.weight" inputmode="decimal" /></div><div class="form-group"><label>体脂 (%)</label><input v-model="form.bodyFat" inputmode="decimal" /></div><div class="form-group"><label>腰围 (cm)</label><input v-model="form.waist" inputmode="decimal" /></div></div><div class="form-group"><label>备注</label><input v-model="form.note" /></div><button class="btn btn-primary">保存指标</button></form><article class="card"><div class="card-title">最近指标</div><div v-if="metrics.length" class="fitness-metric-list"><div v-for="item in metrics" :key="String(item.id)" class="fitness-metric-row"><strong>{{ item.date }}</strong><span v-if="item.weight">体重 {{ item.weight }} kg</span><span v-if="item.bodyFat">体脂 {{ item.bodyFat }}%</span><span v-if="item.waist">腰围 {{ item.waist }} cm</span><span>{{ item.note }}</span></div></div><div v-else class="empty-state">还没有身体指标记录。</div></article></section></template>
