<script setup lang="ts">
import { computed, reactive } from 'vue';
import { genId, getNowLocal, getTodayStr } from '../services/legacyServices';
import { useLifePlanStore } from '../stores/lifePlanStore';
const store = useLifePlanStore(); const form = reactive({ name: '', period: '年度', target: '', status: '进行中' });
const goals = computed(() => store.data.goals.slice().sort((a, b) => Number(b.progress || 0) - Number(a.progress || 0)));
function add() { if (!form.name.trim()) return; const now = getNowLocal(); store.data.goals.unshift({ id: genId(), name: form.name.trim(), period: form.period, target: form.target, status: form.status, progress: 0, createDate: getTodayStr(), createdAt: now, updatedAt: now }); store.commit('create-goal'); Object.assign(form, { name: '', period: '年度', target: '', status: '进行中' }); }
function update(goal: Record<string, unknown>) { goal.updatedAt = getNowLocal(); if (goal.status === '已完成') goal.progress = 100; store.commit('update-goal'); }
function remove(id: string) { const goal = store.data.goals.find(item => item.id === id); if (!goal) return; store.data.deletedItems.push({ collection: 'goals', id, deletedAt: getNowLocal(), reason: 'vue-delete-goal' }); store.data.goals = store.data.goals.filter(item => item.id !== id); store.commit('delete-goal'); }
</script>
<template><section class="page active" id="page-goals"><header class="page-header"><div class="page-title">目标管理</div></header><form class="card" @submit.prevent="add"><div class="form-row"><div class="form-group"><label>目标</label><input v-model="form.name" required /></div><div class="form-group"><label>周期</label><select v-model="form.period"><option>季度</option><option>年度</option><option>长期</option></select></div><div class="form-group"><label>目标描述</label><input v-model="form.target" /></div><div class="form-group"><label>状态</label><select v-model="form.status"><option>进行中</option><option>暂停</option><option>已完成</option></select></div></div><button class="btn btn-primary">新建目标</button></form><div class="goal-grid"><article v-for="goal in goals" :key="String(goal.id)" class="goal-card"><div><h2>{{ goal.name }}</h2><p>{{ goal.period }} · {{ goal.target }}</p></div><div class="form-group"><label>状态</label><select v-model="goal.status" @change="update(goal)"><option>进行中</option><option>暂停</option><option>已完成</option></select></div><div class="form-group"><label>进度 {{ Number(goal.progress || 0) }}%</label><input v-model.number="goal.progress" type="range" min="0" max="100" @change="update(goal)" /></div><button class="btn btn-danger" @click="remove(String(goal.id))">删除</button></article></div><div v-if="!goals.length" class="empty-state">创建第一个目标吧。</div></section></template>
