<script setup lang="ts">
import { computed, ref } from 'vue';
import { useRecordsStore } from '../stores/recordsStore';
import { useTodosStore } from '../stores/todosStore';
const records = useRecordsStore(); const todos = useTodosStore();
const query = ref(''); const status = ref('all'); const title = ref(''); const content = ref('');
const ideas = computed(() => records.services.records.filterIdeas(records.ideas, { keyword: query.value, statusFilter: status.value, hasMatchingTag: (tags: string[], tag: string) => !tag || tags.some(item => item.includes(tag)), getRecordSortValue: (item: Record<string, unknown>) => String(item.updatedAt || item.createdAt || '') }));
function add() { if (!title.value.trim()) return; records.addIdea(title.value.trim(), content.value); title.value = ''; content.value = ''; }
function convert(idea: Record<string, unknown>) { if (idea.ideaTodoId) return; const todo = todos.create({ text: records.services.records.getIdeaTodoText(idea), note: records.services.records.getIdeaTodoNote(idea), dueDate: '', planStartDate: '', planEndDate: '', urgency: 'medium', group: '灵感' }); records.linkIdeaTodo(String(idea.id), todo.id); }
</script>
<template><section class="page active" id="page-ideas"><header class="page-header"><div class="page-title">灵感池</div></header><form class="card" @submit.prevent="add"><div class="form-row"><div class="form-group"><label>新灵感</label><input v-model="title" required placeholder="先接住这个想法" /></div><div class="form-group"><label>补充</label><input v-model="content" placeholder="可选说明" /></div></div><button class="btn btn-primary">加入灵感池</button></form><div class="filter-bar"><input v-model="query" type="search" placeholder="搜索灵感" /><select v-model="status"><option value="all">全部状态</option><option v-for="item in ['待整理','待实践','实践中','已验证','已放弃']" :key="item" :value="item">{{ item }}</option></select></div><div v-if="ideas.length" class="idea-grid"><article v-for="idea in ideas" :key="idea.id" :class="['idea-card', `status-${idea.ideaStatus || '待整理'}`]"><div class="idea-card-head"><h2>{{ idea.title || '无标题灵感' }}</h2><select :value="idea.ideaStatus || '待整理'" @change="records.setIdeaStatus(String(idea.id), ($event.target as HTMLSelectElement).value)"><option v-for="item in ['待整理','待实践','实践中','已验证','已放弃']" :key="item">{{ item }}</option></select></div><p>{{ idea.content }}</p><div class="idea-card-actions"><button class="btn btn-secondary" type="button" @click="convert(idea)">{{ idea.ideaTodoId ? '已关联待办' : '转成待办' }}</button><button class="btn btn-danger" type="button" @click="records.remove('records', String(idea.id))">删除</button></div></article></div><div v-else class="empty-state">还没有匹配的灵感。</div></section></template>
