<script setup lang="ts">
import { reactive, ref } from 'vue';
import { createLegacyServices } from '../services/legacyServices';
import { useLifePlanStore } from '../stores/lifePlanStore';
import { lifePlanRepository } from '../services/lifePlanRepository';
const store = useLifePlanStore(); const sync = createLegacyServices().sync;
const config = reactive({ webdavUrl: '', remotePath: '/life-plan.json', autoSync: true, ...JSON.parse(localStorage.getItem('lifePlanSyncConfig') || '{}') }); const status = ref(''); const busy = ref(false);
function saveConfig() { if (!config.remotePath.startsWith('/')) config.remotePath = `/${config.remotePath}`; localStorage.setItem('lifePlanSyncConfig', JSON.stringify(config)); status.value = '配置已保存到原 lifePlanSyncConfig。'; }
async function pullAndMerge() { busy.value = true; status.value = ''; try { const remote = await sync.pullJson(config, config.remotePath); if (!remote) { status.value = '远端文件不存在或为空，未修改本地数据。'; return; } lifePlanRepository.createSnapshot('云端合并前自动备份', store.data, { action: 'before-merge', mergedWith: { label: '云端', hash: remote.hash } }); const merged = sync.mergeCloudData(store.data, remote.data); lifePlanRepository.createSnapshot('云端合并结果', merged, { action: 'merge-result', mergedWith: { label: '云端', hash: remote.hash } }); store.replace(merged, 'cloud-merge', 'sync'); localStorage.setItem('lifePlanSyncState', JSON.stringify({ ...(JSON.parse(localStorage.getItem('lifePlanSyncState') || '{}')), lastRemoteHash: remote.hash, lastRemoteEtag: remote.etag, lastPullAt: new Date().toISOString(), lastSyncAt: new Date().toISOString(), dirty: false })); status.value = '已按原 mergeCloudData 规则合并云端数据。'; } catch (error) { status.value = error instanceof Error ? error.message : String(error); } finally { busy.value = false; } }
async function push() { busy.value = true; status.value = ''; try { const response = await sync.pushJson(config, config.remotePath, store.data, 'life-plan'); const hash = sync.getDataHash(store.data); localStorage.setItem('lifePlanSyncState', JSON.stringify({ ...(JSON.parse(localStorage.getItem('lifePlanSyncState') || '{}')), lastRemoteHash: hash, lastRemoteEtag: response.etag, lastPushAt: new Date().toISOString(), lastSyncAt: new Date().toISOString(), dirty: false })); status.value = '主数据已上传到原 /life-plan.json 路径。'; } catch (error) { status.value = error instanceof Error ? error.message : String(error); } finally { busy.value = false; } }
async function importFile(event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (!file) return; try { store.importData(JSON.parse(await file.text())); status.value = '导入已按合并规则完成，并建立前后快照。'; } catch (error) { status.value = error instanceof Error ? error.message : String(error); } finally { (event.target as HTMLInputElement).value = ''; } }
</script>
<template><section class="page active"><header class="page-header"><div class="page-title">云同步</div></header><article class="card"><div class="card-title">主数据 WebDAV 配置</div><div class="form-row"><div class="form-group"><label>同步地址</label><input v-model="config.webdavUrl" placeholder="https://…" /></div><div class="form-group"><label>远端路径</label><input v-model="config.remotePath" /></div></div><button class="btn btn-secondary" @click="saveConfig">保存配置</button></article><article class="card"><div class="card-title">备份与导入</div><p>导出的是原有完整 `lifePlanData` 格式。导入不是覆盖操作，会保留原有合并和快照保护。</p><div class="page-actions"><button class="btn btn-secondary" @click="store.exportData">导出备份</button><label class="btn btn-secondary">导入并合并<input hidden type="file" accept="application/json" @change="importFile" /></label></div></article><article class="card"><div class="card-title">手动同步</div><p>合并下载会在合并前、后各创建原格式本地快照，并调用现有 `mergeCloudData`，不会以覆盖逻辑替代冲突处理。</p><div class="page-actions"><button class="btn btn-secondary" :disabled="busy || !config.webdavUrl" @click="pullAndMerge">下载并合并</button><button class="btn btn-primary" :disabled="busy || !config.webdavUrl" @click="push">上传主数据</button></div><p v-if="status" class="sync-status active">{{ status }}</p></article></section></template>
