<script setup lang="ts">
import { computed, ref } from 'vue';
import { genId, getNowLocal } from '../services/legacyServices';
import { useLifePlanStore } from '../stores/lifePlanStore';
import { useTodosStore } from '../stores/todosStore';
const store = useLifePlanStore(); const todos = useTodosStore(); const selectedId = ref(''); const result = ref<any>(null);
const wheels = computed(() => store.data.wheels); const selected = computed(() => wheels.value.find(item => item.id === selectedId.value) || wheels.value[0]);
type WheelOption = { id?: string; name?: string; weight?: number; enabled?: boolean; tagIds?: string[] };
const options = computed<WheelOption[]>(() => { const wheel = selected.value; if (!wheel) return []; const tags = Array.isArray(wheel.tagIds) ? wheel.tagIds as string[] : []; if (wheel.mode === 'tag') return store.data.wheelLibraryItems.filter(item => item.enabled !== false && (Array.isArray(item.tagIds) ? item.tagIds as string[] : []).some(id => tags.includes(id))) as WheelOption[]; return (Array.isArray(wheel.items) ? wheel.items : []).filter((item: WheelOption) => item.enabled !== false) as WheelOption[]; });
function spin() { const items = options.value; if (!items.length || !selected.value) return; const total = items.reduce((sum: number, item: WheelOption) => sum + Math.max(1, Number(item.weight || 1)), 0); let cursor = Math.random() * total; const picked = items.find((item: WheelOption) => (cursor -= Math.max(1, Number(item.weight || 1))) <= 0) || items[items.length - 1]; result.value = picked; store.mutate('wheel-spin', data => data.wheelHistory.unshift({ id: genId(), wheelId: String(selected.value?.id || ''), wheelName: String(selected.value?.name || ''), mode: String(selected.value?.mode || 'normal'), resultId: picked.id || '', resultName: picked.name || '未命名结果', note: '', createdAt: getNowLocal(), updatedAt: getNowLocal() })); }
function createTodo() { if (!result.value) return; todos.create({ text: `执行转盘结果：${result.value.name}`, note: '', dueDate: '', planStartDate: '', planEndDate: '', urgency: 'medium', group: '转盘' }); }
</script>
<template><section class="page active" id="page-wheel"><header class="page-header"><div class="page-title">工具转盘</div></header><article class="card"><div class="form-group"><label>选择转盘</label><select v-model="selectedId"><option v-for="wheel in wheels" :key="String(wheel.id)" :value="String(wheel.id)">{{ wheel.name }}</option></select></div><div class="wheel-stage"><div class="wheel-result">{{ result?.name || '准备开始' }}</div><button class="btn btn-primary" :disabled="!options.length" @click="spin">开始转动</button><button v-if="result" class="btn btn-secondary" @click="createTodo">转为待办</button></div><p v-if="!options.length" class="empty-state">当前转盘没有启用的选项。</p></article><article class="card"><div class="card-title">最近记录</div><div v-for="entry in store.data.wheelHistory.slice(0, 10)" :key="String(entry.id)" class="wheel-history-row">{{ entry.resultName }} · {{ entry.createdAt }}</div></article></section></template>
