<script setup lang="ts">
import { computed } from 'vue';
import { addDays, formatMinutesLabel, getMonthEnd, getWeekStart, layoutTimedItems, sortScheduleItems, type ScheduleItem } from '../utils/schedule';

const props = defineProps<{ mode: 'day' | 'week' | 'month'; cursor: string; items: ScheduleItem[] }>();
const emit = defineEmits<{ select: [item: ScheduleItem] }>();
const today = new Date().toISOString().slice(0, 10);
const dates = computed(() => { if (props.mode === 'day') return [props.cursor]; if (props.mode === 'week') { const start = getWeekStart(props.cursor); return Array.from({ length: 7 }, (_, index) => addDays(start, index)); } const start = getWeekStart(`${props.cursor.slice(0, 7)}-01`); const end = getMonthEnd(props.cursor); const gridEnd = addDays(end, 7 - ((new Date(`${end}T12:00:00`).getDay() || 7))); const values: string[] = []; for (let date = start; date <= gridEnd; date = addDays(date, 1)) values.push(date); return values; });
const byDate = computed<Record<string, ScheduleItem[]>>(() => props.items.reduce<Record<string, ScheduleItem[]>>((groups, item) => { (groups[item.date] ??= []).push(item); return groups; }, {}));
const hours = Array.from({ length: 18 }, (_, index) => index + 6);
function style(item: ScheduleItem, mode: 'day' | 'week') { const heightPerHour = mode === 'day' ? 62 : 54; const start = item.startMinutes ?? 0; const end = item.endMinutes && item.endMinutes > start ? item.endMinutes : start; const height = Math.max((end - start) * heightPerHour / 60, item.endMinutes ? 22 : 18); const cols = item.layoutColumns || 1; const column = item.layoutColumn || 0; const gap = mode === 'day' ? 6 : 2; const width = mode === 'day' ? '160px' : `calc((100% - 8px - ${gap * (cols - 1)}px) / ${cols})`; const left = mode === 'day' ? `${4 + (160 + gap) * column}px` : `calc(4px + (${width} + ${gap}px) * ${column})`; return { top: `${Math.max((start - 360) * heightPerHour / 60, 0)}px`, height: `${height}px`, left, width, '--event-bg': item.tone.bg, '--event-border': item.tone.border, '--event-ink': item.tone.ink }; }
function title(item: ScheduleItem) { const time = item.startMinutes === null ? '全天' : `${formatMinutesLabel(item.startMinutes)}${item.endMinutes ? ` - ${formatMinutesLabel(item.endMinutes)}` : ''}`; return `${time} ${item.title}`; }
</script>

<template>
  <div v-if="mode === 'month'" class="record-calendar"><div class="calendar-grid"><div v-for="name in ['周一','周二','周三','周四','周五','周六','周日']" :key="name" class="calendar-head">{{ name }}</div><div v-for="date in dates" :key="date" :class="['calendar-cell', { 'is-today': date === today }]"><div class="calendar-date"><span>{{ Number(date.slice(-2)) }}</span><small>{{ date === today ? '今天' : '' }}</small></div><div class="calendar-cell-body"><button v-for="item in sortScheduleItems(byDate[date] || []).slice(0, 5)" :key="item.key" type="button" :title="title(item)" class="calendar-event" :class="{ 'is-done': item.done }" :style="{ '--event-bg': item.tone.bg, '--event-border': item.tone.border, '--event-ink': item.tone.ink }" @click="emit('select', item)">{{ item.startMinutes === null ? '' : `${formatMinutesLabel(item.startMinutes)} ` }}{{ item.title }}</button><div v-if="(byDate[date] || []).length > 5" class="calendar-more">还有 {{ (byDate[date] || []).length - 5 }} 项</div></div></div></div></div>
  <div v-else :class="['agenda-shell', `agenda-${mode}`]" :style="{ '--agenda-hour-height': `${mode === 'day' ? 62 : 54}px` }"><div class="agenda-head" :style="{ gridTemplateColumns: `72px repeat(${dates.length}, minmax(0, 1fr))` }"><div class="agenda-corner"></div><div v-for="date in dates" :key="date" :class="['agenda-day-head', { 'is-today': date === today }]"><div class="agenda-day-label">{{ ['周日','周一','周二','周三','周四','周五','周六'][new Date(`${date}T12:00:00`).getDay()] }}</div><div><span class="agenda-day-number">{{ Number(date.slice(-2)) }}</span><span v-if="date === today" class="agenda-day-extra">今天</span></div></div></div><div class="agenda-all-day" :style="{ gridTemplateColumns: `72px repeat(${dates.length}, minmax(0, 1fr))` }"><div class="agenda-all-day-label">全天事项</div><div v-for="date in dates" :key="date" class="agenda-all-day-cell"><button v-for="item in sortScheduleItems((byDate[date] || []).filter(item => item.allDay)).slice(0, 3)" :key="item.key" type="button" class="agenda-all-day-item" :class="{ 'is-done': item.done }" :title="title(item)" :style="{ '--event-bg': item.tone.bg, '--event-border': item.tone.border, '--event-ink': item.tone.ink }" @click="emit('select', item)">{{ item.title }}</button></div></div><div class="agenda-body"><div class="agenda-time-axis"><div v-for="hour in hours" :key="hour" class="agenda-hour-label">{{ String(hour).padStart(2, '0') }}:00</div></div><div class="agenda-columns"><div class="agenda-columns-grid" :style="{ gridTemplateColumns: `repeat(${dates.length}, minmax(0, 1fr))` }"><div v-for="date in dates" :key="date" class="agenda-day-column"> <div v-for="hour in hours" :key="hour" class="agenda-hour-slot"></div><div class="agenda-event-layer"><button v-for="item in layoutTimedItems((byDate[date] || []).filter(item => !item.allDay))" :key="item.key" type="button" class="agenda-event-block" :class="{ 'is-short': (item.endMinutes || item.startMinutes || 0) - (item.startMinutes || 0) < 46, 'is-done': item.done }" :style="style(item, mode)" :title="title(item)" @click="emit('select', item)"><span class="agenda-event-time">{{ formatMinutesLabel(item.startMinutes) }}</span><span class="agenda-event-title">{{ item.title }}</span><span v-if="item.meta" class="agenda-event-meta">{{ item.meta }}</span></button></div></div></div></div></div></div>
</template>
